#
#  Copyright 2021 DataStax, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

# Please note that this example works only with Luna Streaming 2.8.0.1.1.5+

# Customize the value of kafkaAdvertisedListeners in order to reflect the actual advertised name for your Proxy service
image:
  broker:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  brokerSts:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  function:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  zookeeper:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  bookkeeper:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  proxy:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: Always
    tag: latest-272
  bastion:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  pulsarBeam:
    repository: kesque/pulsar-beam
    pullPolicy: IfNotPresent
    tag: 1.0.0
  burnell:
    repository: datastax/burnell
    pullPolicy: Always
    tag: 1.0.0
  burnellLogCollector:
    repository: datastax/burnell
    pullPolicy: IfNotPresent
    tag: logcollector_latest
  pulsarSQL:
    repository: harbor.sjc.dsinternal.org/pulsar/lunastreaming-all
    pullPolicy: IfNotPresent
    tag: latest-272
  tardigrade:
    repository: storjlabs/gateway
    pullPolicy: IfNotPresent
    tag: latest
  pulsarHeartbeat:
    repository: datastax/pulsar-heartbeat
    pullPolicy: IfNotPresent
    tag: 1.0.2
  pulsarAdminConsole:
    repository: datastax/pulsar-admin-console
    pullPolicy: IfNotPresent
    tag: 1.0.0

enableAntiAffinity: false
enableTls: false
enableTokenAuth: true
restartOnConfigMapChange:
  enabled: true
extra:
  function: true
  burnell: true
  burnellLogCollector: true
  pulsarHeartbeat: true
  pulsarAdminConsole: true

cert-manager:
  enabled: true

createCertificates:
  selfSigned:
    enabled: true

zookeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 300Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms300m -Xmx300m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError\""

bookkeeper:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    BOOKIE_MEM: "\"-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError\""

broker:
  component: broker
  service:
    annotations: {}
    type: ClusterIP
    headless: false
    ports:
    - name: http
      port: 8080
    - name: pulsar
      port: 6650
    - name: https
      port: 8443
    - name: pulsarssl
      port: 6651
    - name: kafkaplaintext
      port: 9092
    - name: kafkassl
      port: 9093
  replicaCount: 2
  ledger:
    defaultEnsembleSize: 1
    defaultAckQuorum: 1
    defaultWriteQuorum: 1
  resources:
    requests:
      memory: 200Mi
      cpu: 0.1
  configData:
    PULSAR_MEM: "\"-Xms400m -Xmx400m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError\""
  kafkaOnPulsarEnabled: true
  kafkaOnPulsar:    
    saslAllowedMechanisms: PLAIN
    brokerEntryMetadataInterceptors: "org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor,org.apache.pulsar.common.intercept.AppendBrokerTimestampMetadataInterceptor"

autoRecovery:
  enableProvisionContainer: yes
  resources:
    requests:
      memory: 300Mi
      cpu: 0.3


function:
  replicaCount: 1
  functionReplicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError\""

proxy:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  wsResources:
    requests:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "\"-Xms400m -Xmx400m -XX:MaxDirectMemorySize=112m\""
    PULSAR_PREFIX_kafkaListeners: "SASL_PLAINTEXT://0.0.0.0:9092,SASL_SSL://0.0.0.0:9093"
    PULSAR_PREFIX_kafkaAdvertisedListeners: "SASL_PLAINTEXT://pulsar-proxy:9092,SASL_SSL://pulsar-proxy:9093"
    PULSAR_PREFIX_saslAllowedMechanisms: PLAIN
    PULSAR_PREFIX_kafkaProxySuperUserRole: superuser
  autoPortAssign:
    enablePlainTextWithTLS: true
  service:
    type: ClusterIP
    autoPortAssign:
      enabled: true
  protocolHandlers:
    enabled: true
    protocols: "kafka"
    containerPorts:
      - name: kafkaplaintext
        containerPort: 9092
      - name: kafkassl
        containerPort: 9093
    servicePorts:
     - name: kafkaplaintext
       port: 9092
       protocol: TCP
       targetPort: kafkaplaintext
     - name: kafkassl
       port: 9093
       protocol: TCP
       targetPort: kafkassl      
pulsarAdminConsole:
  replicaCount: 1
  service:
    type: ClusterIP
grafana: #ASF Helm Chart
  service:
    type: ClusterIP
pulsar_manager:
  service: #ASF Helm Chart
    type: ClusterIP
kube-prometheus-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  grafana:
    enabled: false
    adminPassword: e9JYtk83*4#PM8
    service:
      type: ClusterIP
grafanaDashboards:
  enabled: false
